project_name: determined-master

before:
  hooks:
    - make pre-package

snapshot:
  name_template: "{{ .Tag }}"

builds:
  - main: ./cmd/determined-master
    ldflags:
      - -X github.com/determined-ai/determined/master/version.Version={{.Env.VERSION}}
      - -X github.com/determined-ai/determined/master/internal.DefaultSegmentMasterKey={{.Env.DET_SEGMENT_MASTER_KEY}}
      - -X github.com/determined-ai/determined/master/internal.DefaultSegmentWebUIKey={{.Env.DET_SEGMENT_WEBUI_KEY}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - ppc64
  - main: ./cmd/determined-gotmpl
    id: determined-gotmpl
    binary: determined-gotmpl
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - ppc64

archives:
  - wrap_in_directory: true
    files:
      - "share/determined/master/**/*"

nfpms:
  - maintainer: "Determined AI <hello@determined.ai>"
    formats:
      - deb
      - rpm
    config_files:
      "packaging/master.yaml": "/etc/determined/master.yaml"
      "packaging/prometheus.yml": "/etc/determined/prometheus.yml"
    files:
      "build/**/*": "/usr/share/determined/master"
      "static/**/*": "/usr/share/determined/master/static"
      "packaging/determined-master.service": "/lib/systemd/system/determined-master.service"
      "packaging/determined-prom.service": "/lib/systemd/system/determined-prom.service"
    overrides:
      deb:
        scripts:
          postinstall: packaging/debian/master.postinst
          preremove: packaging/debian/master.prerm
          postremove: packaging/debian/master.postrm
        files:
          "packaging/LICENSE": "/usr/share/doc/determined-master/copyright"
      rpm:
        files:
          "packaging/LICENSE": "/usr/share/licenses/determined-master/LICENSE"

release:
  github:
    owner: determined-ai
    name: determined

