description: mnist_tf_core_to_estimator
hyperparameters:
  learning_rate: 1e-3
  global_batch_size: 64
  n_filters_1: 10
  n_filters_2: 40
searcher:
  name: single
  metric: error
  smaller_is_better: true
  max_length:
    batches: 2000
entrypoint: model_def:MNistTrial
environment:
  image: determinedai/environments:cuda-11.0-pytorch-1.7-tf-2.4-gpu-0.9.0
